import { createContext, useState } from "react";

export const AppContext = createContext();

const AppContextProvider = ({ children }) => {
  const [products, setProducts] = useState([
    // ===== MEN CATEGORY - Collection of 10 male fashion products =====
    {
      id: 1,
      name: "Men's Snapback Cap",
      price: 800,
      category: "Men",
      subCategory: "Caps",
      images: "/images/caps.jpg",
      description: "Premium cotton snapback with adjustable strap.",
      colors: ["Black"],
      sizes: ["Free"],
    },
    {
      id: 2,
      name: "Classic Formal Shirt",
      price: 2200,
      category: "Men",
      subCategory: "Dress",
      images: "/images/catImg/cap.jpg",
      description: "Slim fit formal shirt for office wear.",
      colors: ["White"],
      sizes: ["M", "L", "XL"],
    },
    {
      id: 3,
      name: "Men's Mesh Shoes",
      price: 4500,
      category: "Men",
      subCategory: "Shoes",
      images: "/images/caps.jpg",
      description: "Breathable lightweight shoes for gym.",
      colors: ["Blue"],
      sizes: ["9", "10"],
    },
    {
      id: 4,
      name: "Men's Luxury Watch",
      price: 8000,
      category: "Men",
      subCategory: "Watches",
      images: "/images/listImg/1.jpg",
      description: "Stainless steel luxury watch for men.",
      colors: ["Silver"],
      sizes: ["Standard"],
    },
    {
      id: 5,
      name: "Slim Fit Cargo",
      price: 2800,
      category: "Men",
      subCategory: "Bottoms",
      images: "/images/caps.jpg",
      description: "Stylish cargo pants with multiple pockets.",
      colors: ["Olive Green"],
      sizes: ["32", "34"],
    },
    {
      id: 6,
      name: "Urban Trucker Hat",
      price: 900,
      category: "Men",
      subCategory: "Caps",
      images: "/images/caps.jpg",
      description: "Cool trucker hat for summer.",
      colors: ["Grey"],
      sizes: ["Free"],
    },
    {
      id: 7,
      name: "Cotton Chinos",
      price: 1800,
      category: "Men",
      subCategory: "Bottoms",
      images: "/images/listImg/2.jpg",
      description: "Perfect for semi-formal occasions.",
      colors: ["Tan"],
      sizes: ["30", "32"],
    },
    {
      id: 8,
      name: "Denim Jacket",
      price: 3500,
      category: "Men",
      subCategory: "Dress",
      images: "/images/caps.jpg",
      description: "Rugged denim jacket for winter.",
      colors: ["Indigo"],
      sizes: ["L", "XL"],
    },
    {
      id: 9,
      name: "Sports Sneakers",
      price: 3200,
      category: "Men",
      subCategory: "Shoes",
      images: "/images/banner.png",
      description: "Durable sneakers for daily use.",
      colors: ["White"],
      sizes: ["8", "9"],
    },
    {
      id: 10,
      name: "Leather Wallet",
      price: 1200,
      category: "Men",
      subCategory: "Watches",
      images: "/images/caps.jpg",
      description: "Genuine leather bifold wallet.",
      colors: ["Brown"],
      sizes: ["NA"],
    },

    // ===== WOMEN CATEGORY - Collection of 10 female fashion products =====
    {
      id: 11,
      name: "Women's Sun Hat",
      price: 1200,
      category: "Women",
      subCategory: "Caps",
      images: "/images/banner.png",
      description: "Wide brim straw hat for beach.",
      colors: ["Beige"],
      sizes: ["Free"],
    },
    {
      id: 12,
      name: "Floral Maxi Dress",
      price: 3500,
      category: "Women",
      subCategory: "Dress",
      images: "/images/caps.jpg",
      description: "Elegant long floral dress.",
      colors: ["Pink"],
      sizes: ["S", "M"],
    },
    {
      id: 13,
      name: "High Heels",
      price: 4000,
      category: "Women",
      subCategory: "Shoes",
      images: "/images/banner.png",
      description: "Pointed toe stilettos.",
      colors: ["Black"],
      sizes: ["7", "8"],
    },
    {
      id: 14,
      name: "Rose Gold Watch",
      price: 5500,
      category: "Women",
      subCategory: "Watches",
      images: "/images/caps.jpg",
      description: "Elegant rose gold plated watch.",
      colors: ["Rose Gold"],
      sizes: ["Standard"],
    },
    {
      id: 15,
      name: "High Waist Leggings",
      price: 1500,
      category: "Women",
      subCategory: "Bottoms",
      images: "/images/banner.png",
      description: "Stretchable yoga leggings.",
      colors: ["Black"],
      sizes: ["M", "L"],
    },
    {
      id: 16,
      name: "Casual Beanie",
      price: 600,
      category: "Women",
      subCategory: "Caps",
      images: "/images/caps.jpg",
      description: "Warm wool beanie for winters.",
      colors: ["Red"],
      sizes: ["Free"],
    },
    {
      id: 17,
      name: "Party Gown",
      price: 6000,
      category: "Women",
      subCategory: "Dress",
      images: "/images/banner.png",
      description: "Heavy work party gown.",
      colors: ["Blue"],
      sizes: ["L"],
    },
    {
      id: 18,
      name: "Flat Sandals",
      price: 1800,
      category: "Women",
      subCategory: "Shoes",
      images: "/images/caps.jpg",
      description: "Comfortable flats for walking.",
      colors: ["Gold"],
      sizes: ["6", "7"],
    },
    {
      id: 19,
      name: "Leather Handbag",
      price: 4500,
      category: "Women",
      subCategory: "Bottoms",
      images: "/images/banner.png",
      description: "Spacious luxury handbag.",
      colors: ["Tan"],
      sizes: ["Large"],
    },
    {
      id: 20,
      name: "Diamond Earrings",
      price: 9000,
      category: "Women",
      subCategory: "Watches",
      images: "/images/caps.jpg",
      description: "Small stud diamond earrings.",
      colors: ["Silver"],
      sizes: ["NA"],
    },

    // ===== KIDS CATEGORY - Collection of 10 children's fashion products =====
    {
      id: 21,
      name: "Kids Cartoon Cap",
      price: 400,
      category: "Kids",
      subCategory: "Caps",
      images: "/images/caps.jpg",
      description: "Fun cap with favorite characters.",
      colors: ["Blue"],
      sizes: ["S"],
    },
    {
      id: 22,
      name: "Baby Girl Party Frock",
      price: 2500,
      category: "Kids",
      subCategory: "Dress",
      images: "/images/banner.png",
      description: "Layered net frock for birthdays.",
      colors: ["Red"],
      sizes: ["22", "26"],
    },
    {
      id: 23,
      name: "Light-up LED Shoes",
      price: 2800,
      category: "Kids",
      subCategory: "Shoes",
      images: "/images/caps.jpg",
      description: "Fun sneakers that glow.",
      colors: ["White"],
      sizes: ["5", "6"],
    },
    {
      id: 24,
      name: "Kids Digital Watch",
      price: 1200,
      category: "Kids",
      subCategory: "Watches",
      images: "/images/banner.png",
      description: "Waterproof digital watch.",
      colors: ["Black"],
      sizes: ["S"],
    },
    {
      id: 25,
      name: "Kids Denim Shorts",
      price: 1000,
      category: "Kids",
      subCategory: "Bottoms",
      images: "/images/caps.jpg",
      description: "Durable denim shorts.",
      colors: ["Blue"],
      sizes: ["24", "26"],
    },
    {
      id: 26,
      name: "Kids Winter Hat",
      price: 500,
      category: "Kids",
      subCategory: "Caps",
      images: "/images/banner.png",
      description: "Pompom winter hat.",
      colors: ["Yellow"],
      sizes: ["Free"],
    },
    {
      id: 27,
      name: "Superhero T-shirt",
      price: 800,
      category: "Kids",
      subCategory: "Dress",
      images: "/images/caps.jpg",
      description: "Cotton superhero printed tee.",
      colors: ["Black"],
      sizes: ["28", "30"],
    },
    {
      id: 28,
      name: "School Backpack",
      price: 1500,
      category: "Kids",
      subCategory: "Bottoms",
      images: "/images/banner.png",
      description: "Lightweight school bag.",
      colors: ["Red"],
      sizes: ["Standard"],
    },
    {
      id: 29,
      name: "Running Shoes Kids",
      price: 2000,
      category: "Kids",
      subCategory: "Shoes",
      images: "/images/caps.jpg",
      description: "Light shoes for playtime.",
      colors: ["Grey"],
      sizes: ["4", "5"],
    },
    {
      id: 30,
      name: "Smart Kids Watch",
      price: 3000,
      category: "Kids",
      subCategory: "Watches",
      images: "/images/banner.png",
      description: "Basic smartwatch with GPS.",
      colors: ["Pink"],
      sizes: ["S"],
    },
  ]);
  const [cartItem, setCartItem] = useState([]);
  const value = {
    products,
    setProducts,
    cartItem,
    setCartItem,
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};

export default AppContextProvider;
